// A string is a subsequence of a given string , that is generated by deleting some 
// characters of a given string without changing its order .

#include <iostream>
#include <vector>
#include <string>
using namespace std;

void printSubsequence(int arr[],int n , int idx , vector <int> ans,int k){

    if(idx == n){
        if(ans.size() == k){ // Only change from subset
            for(int i = 0; i< ans.size();i++){
            cout << ans[i];
        }
        cout << endl;
        }
         return ;
    }
    if(ans.size() + (n-idx) < k) return ; // agar ans size and bache hue array ki 
    // size k se kam hain to code chalane ke jarurat hi nhi 
    printSubsequence(arr,n,idx+1,ans,k);
    ans.push_back(arr[idx]);
    printSubsequence(arr,n,idx+1,ans,k);
}
int main(){
    int arr[] = {1,2,3,4,5};
    int n = sizeof(arr)/ sizeof(arr[0]);
    vector<int> v;
    int k = 3;
    printSubsequence(arr,n,0,v,k);

    return 0;
}
